# name of the software
name: ProtoCentral HeartyPatch

project:
    version: 0.1.0
    download_url: https://github.com/Protocentral/protocentral_heartypatch/releases

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://github.com/Protocentral/protocentral_heartypatch
    footer:
      - title: GitHub
        url: https://github.com/Protocentral/protocentral_heartypatch
      - title: Issues
        url: https://github.com/Protocentral/protocentral_heartypatch/issues?state=open

ui:
    header:
        color1: "#080331"
        color2: "#2b5e77"
        trianglify: true

social:
    github:
        user: protocentral
        repo: protocentral_heartypatch
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
